# Generated by Django 4.2.2 on 2023-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_field1',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='custom_field2',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
