# Generated by Django 4.2.2 on 2023-10-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_field1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='custom_field2',
        ),
    ]
