# Generated by Django 4.2.2 on 2023-10-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='prefecture',
        ),
        migrations.AlterField(
            model_name='thread',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.city'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='deviation_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.deviation_value'),
        ),
    ]
