# Generated by Django 4.2.2 on 2023-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
